version: "3"

services:

  fpm:
    build:
      context: ./
      dockerfile: docker/fpm.Dockerfile
      args:
        UID: 1000
        GID: 1000
    image: "${APP_RUN_NAME}-fpm"
    container_name: "${APP_RUN_NAME}-fpm"
    environment:
      CONTAINER_ROLE: app
      CONTAINER_ENVIRONMENT: development
      LARAVEL_CACHE_ENABLE: 0
    volumes:
      - ./:/app:rw
    links:
      - postgres

  postgres:
    build:
      context: ./
      dockerfile: docker/postgres.Dockerfile
      args:
        UID: 1000
        GID: 1000
    environment:
      POSTGRES_DB: d2
      POSTGRES_USER: d2
      POSTGRES_PASSWORD: d2
      PGDATA: /var/lib/postgresql/data/pgdata
    image: "${APP_RUN_NAME}-postgres"
    container_name: "${APP_RUN_NAME}-postgres"
    volumes:
      - ./var/postgres:/var/lib/postgresql/data/pgdata:rw

